# Generated by Django 4.2.11 on 2026-05-11 17:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_notes_employee_statut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('heure_arrivee', models.TimeField(blank=True, null=True, verbose_name="Heure d'Arrivée")),
                ('selfie_arrivee', models.ImageField(blank=True, null=True, upload_to='attendances/selfies/%Y/%m/%d/', verbose_name='Selfie Arrivée')),
                ('heure_depart', models.TimeField(blank=True, null=True, verbose_name='Heure de Départ')),
                ('selfie_depart', models.ImageField(blank=True, null=True, upload_to='attendances/selfies/%Y/%m/%d/', verbose_name='Selfie Départ')),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('en_retard', 'En Retard'), ('absent', 'Absent'), ('depart_anticipe', 'Départ Anticipé')], default='present', max_length=20)),
                ('qr_code_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token QR Code utilisé')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes / Justifications')),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'db_table': 'attendances',
                'ordering': ['-date', '-heure_arrivee'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
