# Generated by Django 4.2.11 on 2026-05-13 01:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la règle (ex: Matin Salle)')),
                ('poste', models.CharField(choices=[('serveur', 'Serveur / Salle'), ('caissier', 'Caissier'), ('cuisine', 'Cuisine'), ('tout', 'Tous les postes')], default='tout', max_length=50)),
                ('grace_period_minutes', models.IntegerField(default=30, help_text="Nombre de minutes autorisées avant d'être marqué absent.")),
                ('absolute_limit_time', models.TimeField(blank=True, help_text="Heure fixe après laquelle l'employé est d'office absent (ex: 16:30).", null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Règle de pointage',
                'verbose_name_plural': 'Règles de pointage',
                'db_table': 'attendance_rules',
            },
        ),
    ]
