# Generated by Django 4.2.11 on 2026-05-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('caissier', 'Caissier'), ('serveur', 'Serveur'), ('cuisinier', 'Cuisinier')], default='serveur', max_length=20),
        ),
    ]
