# Generated by Django 4.2.11 on 2026-05-13 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Libellé de la dépense')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date de la dépense')),
                ('category', models.CharField(choices=[('nourriture', 'Achats Nourriture'), ('boisson', 'Achats Boissons'), ('entretien', 'Entretien / Nettoyage'), ('energie', 'Gaz / Énergie'), ('autre', 'Autre')], default='nourriture', max_length=50, verbose_name='Catégorie')),
                ('invoice_image', models.ImageField(blank=True, null=True, upload_to='expenses/invoices/%Y/%m/%d/', verbose_name='Photo de la facture')),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé / Payé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes complémentaires')),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par (Cuisinier/Autre)')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validé par (Caissier/Admin)')),
            ],
            options={
                'verbose_name': 'Dépense / Facture',
                'verbose_name_plural': 'Dépenses / Factures',
                'db_table': 'expenses',
                'ordering': ['-inserted_at'],
            },
        ),
    ]
