# Generated by Django 4.2.11 on 2026-05-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='issuer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Donneur'),
        ),
        migrations.AddField(
            model_name='expense',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Récepteur'),
        ),
    ]
