# Generated by Django 4.2.11 on 2026-05-11 17:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_notes_employee_statut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date du service')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('fonction', models.CharField(choices=[('salle_int', 'Salle Intérieure'), ('salle_balcon', 'Salle Balcon'), ('sauce', 'Préparation des Sauces'), ('repos', 'Jour de Repos'), ('caisse', 'Gestion Caisse (Caissiers uniquement)')], default='salle_int', max_length=20, verbose_name='Fonction assignée')),
                ('is_replacement', models.BooleanField(default=False, help_text="Coché automatiquement si l'employé remplace un absent", verbose_name='Est un remplacement ?')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes / Instructions')),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='employees.employee', verbose_name='Employé')),
                ('replaced_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements_made', to='employees.employee', verbose_name='Employé remplacé')),
            ],
            options={
                'verbose_name': 'Planning',
                'verbose_name_plural': 'Plannings',
                'db_table': 'schedules',
                'ordering': ['date', 'heure_debut'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
