# Generated by Django 4.2.11 on 2026-07-22 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0006_employee_salaire_base'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('poste', models.CharField(choices=[('serveur', 'Serveur'), ('caissier', 'Caissier')], max_length=20, verbose_name='Poste concerne')),
                ('jour_semaine', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10, verbose_name='Jour de la semaine')),
                ('nom_equipe', models.CharField(help_text='Ex: Matin, Soir, Soir Equipe A, Soir Equipe B', max_length=50, verbose_name="Nom de l'equipe")),
                ('heure_debut', models.TimeField(verbose_name='Heure de debut')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('tolerance_retard_minutes', models.PositiveIntegerField(default=10, help_text='CONFIDENTIEL : jamais affiche aux employes', verbose_name='Tolerance retard (minutes)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Equipe active')),
            ],
            options={
                'verbose_name': 'Horaire de reference',
                'verbose_name_plural': 'Horaires de reference',
                'db_table': 'shift_schedules',
                'ordering': ['poste', 'jour_semaine', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jour_semaine', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10, verbose_name='Jour de la semaine')),
                ('tache', models.CharField(choices=[('salle_int', 'Salle Interieure'), ('salle_balcon', 'Balcon'), ('caisse', 'Caisse'), ('repos', 'Repos')], default='salle_int', max_length=20, verbose_name='Tache principale du jour')),
                ('fait_sauce_soir', models.BooleanField(default=False, help_text='Additionnel a la tache principale du jour', verbose_name='Fait la sauce ce soir (23h) ?')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('is_replacement', models.BooleanField(default=False, verbose_name='Est un remplacement ?')),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_assignments', to='employees.employee', verbose_name='Employe')),
                ('replaced_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements_made', to='employees.employee', verbose_name='Employe remplace')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='schedules.shiftschedule', verbose_name='Equipe horaire')),
            ],
            options={
                'verbose_name': 'Affectation hebdomadaire',
                'verbose_name_plural': 'Affectations hebdomadaires',
                'db_table': 'weekly_assignments',
                'ordering': ['employee__user__nom', 'jour_semaine'],
                'unique_together': {('employee', 'jour_semaine')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='Message de la demande')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepte'), ('refuse', 'Refuse')], default='en_attente', max_length=15)),
                ('reponse_admin', models.TextField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_changement', to='schedules.weeklyassignment', verbose_name='Affectation concernee')),
                ('demande_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_faites', to='employees.employee', verbose_name='Demande par')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de changement',
                'verbose_name_plural': 'Demandes de changement',
                'db_table': 'schedule_change_requests',
                'ordering': ['-inserted_at'],
            },
        ),
        migrations.CreateModel(
            name='SauceValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(limit_choices_to={'fait_sauce_soir': True}, on_delete=django.db.models.deletion.CASCADE, related_name='validations_sauce', to='schedules.weeklyassignment', verbose_name='Affectation sauce concernee')),
                ('valide_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sauces_validees', to=settings.AUTH_USER_MODEL, verbose_name='Valide par')),
            ],
            options={
                'verbose_name': 'Validation de sauce',
                'verbose_name_plural': 'Validations de sauce',
                'db_table': 'sauce_validations',
                'ordering': ['-date_validation'],
            },
        ),
    ]
