# Generated by Django 4.2.11 on 2026-05-19 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_salaire_base'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['employee__user__nom'], 'verbose_name': 'Planning Fixe', 'verbose_name_plural': 'Plannings Fixes'},
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='schedule',
            name='jours_repos',
            field=models.CharField(blank=True, help_text='Ex: Lundi, Mardi', max_length=100, null=True, verbose_name='Jours de repos'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='employees.employee', verbose_name='Employé'),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
    ]
