# Generated by Django 4.2.11 on 2026-05-11 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('poste', models.CharField(choices=[('SERVEUR', 'Serveur'), ('CUISINIER', 'Cuisinier'), ('PLONGEUR', 'Plongeur'), ('MANAGER', 'Manager'), ('CAISSIER', 'Caissier')], default='SERVEUR', max_length=20)),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire de base')),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['-inserted_at'],
            },
        ),
    ]
