# Generated by Django 4.2.11 on 2026-05-11 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True, help_text='Informations complémentaires sur cet employé', null=True, verbose_name='Notes internes'),
        ),
        migrations.AddField(
            model_name='employee',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('demission', 'Demission'), ('renvoi', 'Renvoi'), ('conge', 'En congé')], default='actif', max_length=10, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_embauche',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'embauche"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='inserted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='poste',
            field=models.CharField(choices=[('serveur', 'Serveur / Serveuse'), ('caissier', 'Caissier / Caissière'), ('admin', 'Administrateur')], default='serveur', max_length=20, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salaire_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Salaire de base'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['statut'], name='idx_employee_statut'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['poste'], name='idx_employee_poste'),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employees',
        ),
    ]
