# Generated by Django 4.2.11 on 2026-05-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_notes_employee_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='taux_horaire',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Utilisé pour calculer la paie basée sur les heures réelles', max_digits=10, verbose_name='Taux horaire'),
        ),
        migrations.AddField(
            model_name='employee',
            name='type_contrat',
            field=models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('extra', 'Extra / Journalier'), ('stage', 'Stagiaire')], default='cdi', max_length=20, verbose_name='Type de contrat'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salaire_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Salaire de base (Mensuel)'),
        ),
    ]
