# Generated by Django 4.2.11 on 2026-05-13 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_taux_horaire_employee_type_contrat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salaire_base',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='taux_horaire',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='type_contrat',
        ),
    ]
