# Generated by Django 4.2.11 on 2026-05-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_employee_salaire_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='poste',
            field=models.CharField(choices=[('serveur', 'Serveur / Serveuse'), ('caissier', 'Caissier / Caissière'), ('cuisine', 'Cuisinier / Cuisine'), ('admin', 'Administrateur')], default='serveur', max_length=20, verbose_name='Poste'),
        ),
    ]
