# Generated by Django 4.2.11 on 2026-05-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salaire_base',
            field=models.PositiveIntegerField(default=0, help_text='Montant fixe en FG', verbose_name='Salaire de Base'),
        ),
    ]
